name: 0. Deployment environnment Lab_3

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: "RG-Lab3"
  LOCATION: "eastus2"
  CONTAINERAPPS_ENVIRONMENT: "environment-lab-3"
  LOG_ANALYTICS_NAME: "zol-workspace-lab-3"
  ACR_NAME: "acrlab3zol"
  ##################################################################################################################################################################################
  # Nous sommes dans un Workshop !                                                                                                                                                 #
  # Dans les bonnes pratiques, toutes la informations liées à la base de données sont à mettre dans un service pour stocker les secrets (ex: service secrets GitHub, KeyVault, ...)#
  DB_HOST_NAME: "DB-lab-3-zol"                                                                                                                                                     #
  DB_NAME: "rugby_api" # ne pas modifier                                                                                                                                           #
  DB_ADMIN: "zoloc"                                                                                                                                                               #
  DB_ADMIN_PASSWORD: Password123$                                                                                                                                                  #
  ##################################################################################################################################################################################

jobs:
  Deployment-environnment:
    runs-on: ubuntu-latest

    steps:
      - name: Create "Table"
        uses: azure/mysql@093f3af08a63a1d99485a1d93d3771b684625875
        with:
          server-name: ${{ env.DB_HOST_NAME }}.mysql.database.azure.com
          username: ${{ env.DB_ADMIN }}@${{ env.DB_HOST_NAME }}
          password: ${{ env.DB_ADMIN_PASSWORD }}
          database: ${{ env.DB_NAME }}
          sql-file: './Lab_3/App/db/create_tables.sql'
